AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Parser:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: python2.7
      Timeout: 120
      MemorySize: 512
      Policies:
      # Give just CRUD permissions to one table
      - DynamoDBCrudPolicy:
          TableName: !Ref EventsTable
      Environment:
        Variables:
          DDB_TABLE: !Ref EventsTable
          CRAWLER_DAYS: 7

  EventsTable:
    Type: 'AWS::Serverless::SimpleTable'
